ElectronDecanat/ElectronDecanat/Controllers/DekanController.cs
using ElectronDecanat.Code;
using ElectronDecanat.Repozitory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectronDecanat.Controllers
{
    [Authorize(Roles = "decanat")]
    public class DekanController : Controller
    {
        public ActionResult Facultes()
        {
            return View(UnitOfWork.Faculties.GetAll());
        }
        public ActionResult Specialitis(int faculty_id)
        {
            ViewBag.faculty_id = faculty_id;
            ViewBag.faculty = UnitOfWork.Faculties.Get(faculty_id).Name;
            return View(UnitOfWork.Specialitys.GetAll("where \"Код_факультета\"=" + faculty_id));
        }
        public ActionResult Subgroups(int speciality_id)
        {
            Speciality speciality = UnitOfWork.Specialitys.Get(speciality_id);
            ViewBag.faculty_id = speciality.faculty_code;
            ViewBag.faculty = speciality.faculty_name;
            ViewBag.speciality_name = speciality.speciality_name;
            ViewBag.speciality_number = speciality.speciality_number;
            ViewBag.speciality_id = speciality.id;
            return View(UnitOfWork.Subgroups.GetAll("where \"Код_специальности\"=" + speciality_id));
        }
        public ActionResult Studing(int subgroup_id, int speciality_id)
        {
            Subgroup subgroup = UnitOfWork.Subgroups.Get(subgroup_id);
            ViewBag.faculty_name = subgroup.faculty_name;
            ViewBag.speciality_name = subgroup.speciality_name;
            ViewBag.speciality_number = subgroup.speciality_number;
            ViewBag.speciality_id = subgroup.speciality_id;
            ViewBag.coors = subgroup.coors;
            ViewBag.group_number = subgroup.group_number;
            ViewBag.subgroup_number = subgroup.subgroup_number;
            return View(UnitOfWork.Studing.GetAll("where \"Код_специальности\"=" + speciality_id + " and \"Код_подгруппы\"=" + subgroup_id));
        }
        public ActionResult DisciplineStuding(int student_id)
        {
            Student student = UnitOfWork.Students.Get(student_id);
            ViewBag.faculty_name = student.faculty_name;
            ViewBag.speciality_name = student.speciality_name;
            ViewBag.speciality_number = student.speciality_number;
            ViewBag.speciality_id = student.speciality_id;
            ViewBag.subgroup_id = student.subgroup_id;
            ViewBag.coors = student.coors;
            ViewBag.group_number = student.group_number;
            ViewBag.subgroup_number = student.subgroup_number;
            ViewBag.student_name = student.FIO;
            return View(UnitOfWork.Studing.GetDisciplines("where \"Код_студента\"=" + student_id));
        }
	}
}

ElectronDecanat/ElectronDecanat/Controllers/MainController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectronDecanat.Code;

namespace ElectronDecanat.Controllers
{
    public class MainController : Controller
    {
        // GET: Main
        public ActionResult Index()
        {
            return View();
            
        }
    }
}

ElectronDecanat/ElectronDecanat/Controllers/StudentController.cs
using ElectronDecanat.Code;
using ElectronDecanat.Repozitory;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace ElectronDecanat.Controllers
{
    public class StudentController : Controller
    {
        // GET: Student
        public ActionResult Index(string name)
        {
            if (!String.IsNullOrWhiteSpace(name))
            {
                ViewBag.querry = name;
                return View(UnitOfWork.Students.GetAll("where \"ФИО\" LIKE '%" + name + "%'"));
            }
            else
            {
                ViewBag.querry = "";
                return View(new List<Student>()); 
            }
        }
        public ActionResult Student(int id, string quarry)
        {
            ViewBag.quarry = quarry;
            IEnumerable<LabProgress> list = UnitOfWork.LabProgress.GetAll("where \"Код_студента\"=" + id + " order by \"Наименование_дисциплины\"");
            if(list.Count()!=0)
            {
                ViewBag.FIO = list.ElementAt(0).student_name;
                ViewBag.coors = list.ElementAt(0).coors;
                ViewBag.group_number = list.ElementAt(0).group_number;
                ViewBag.subgroop_number = list.ElementAt(0).subgroop_number;
            }
            return View(list);
        }
    }
}

ElectronDecanat/ElectronDecanat/Controllers/TeacherController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ElectronDecanat.Code;
using Microsoft.AspNet.Identity;
using ElectronDecanat.Repozitory;
 
 
//https://metanit.com/sharp/mvc5/12.4.php роли


namespace ElectronDecanat.Controllers
{
    [Authorize(Roles = "teacher")]
    public class TeacherController : Controller
    {
        // GET: Teacher
        public ActionResult Index()
        {
            return View(UnitOfWork.Works.GetAll("where \"Код_преподавателя\"='"+User.Identity.GetUserId()+"'"));
        }
        public ActionResult Labs(int discipline_id ,int subgroup_id)
        {
            Subgroup subgroup = UnitOfWork.Subgroups.Get(subgroup_id);
            Discipline discipline = UnitOfWork.Disciplines.Get(discipline_id);
            ViewBag.coors = subgroup.coors;
            ViewBag.group_number = subgroup.group_number;
            ViewBag.subgroup_number = subgroup.subgroup_number;
            ViewBag.discipline_name = discipline.discipline_name;
            IEnumerable<LabProgress> array = UnitOfWork.LabProgress.GetAll("WHERE \"Код_преподавателя\" = '" + User.Identity.GetUserId() + "' AND \"Код_дисциплины\"=" + discipline_id + " and \"Код_подгруппы\"=" + subgroup_id);
            Dictionary<string,List<LabProgress>> grouped_students = new Dictionary<string,List<LabProgress>>();
            List<LabProgress> current_list;
            for(int i=0;i<array.Count();i++)
            {
                if(!grouped_students.ContainsKey(array.ElementAt(i).student_name))
                    grouped_students.Add(array.ElementAt(i).student_name, new List<LabProgress>());
                grouped_students.TryGetValue(array.ElementAt(i).student_name, out current_list);
                current_list.Add(array.ElementAt(i));
            }
            var data = grouped_students.OrderBy(element => element.Key).ToList();
            return View(grouped_students.OrderBy(element => element.Key).ToList());
            
        }
        public ActionResult LabsList()
        {
            List<Discipline> disciplines = UnitOfWork.Disciplines.getTeacherDisciplines(User.Identity.GetUserId());
            return View(disciplines);
        }
        public ActionResult LabsOnDisciplineList(int discipline_id)
        {
            string name = User.Identity.GetUserId();
            ViewBag.discipline_id = discipline_id;
            return View(UnitOfWork.Labs.GetAll("where \"Код_дисциплины\" =" + discipline_id));
        }
        public ActionResult AddLab(int discipline_id)
        {
            Discipline discipline = UnitOfWork.Disciplines.Get(discipline_id);
            Lab lab = new Lab()
            {
                discipline = discipline.discipline_name,
                discipline_id = discipline.id,
                speciality = discipline.speciality_name
            };
            return View(lab);
        }
        [HttpPost]
        public ActionResult AddLab(Lab item)
        {
            try
            {
                UnitOfWork.Labs.Create(item);
                return RedirectToAction("LabsOnDisciplineList", new { discipline_id = item.discipline_id });
            }
            catch
            {
                ModelState.AddModelError("lab_name", "ошибка добавления, возможно такая лабораторная уже есть?");
                return View(item);
            }
        }
        public ActionResult DeleteLab(int id)
        {
            Lab lab = UnitOfWork.Labs.Get(id);
            return View(lab);
        }
        [HttpPost]
        public ActionResult DeleteLab(Lab item)
        {
            try
            {
                UnitOfWork.Labs.Delete(item.id);
                return RedirectToAction("LabsOnDisciplineList", new { discipline_id = item.discipline_id });
            }
            catch
            {
                ModelState.AddModelError("lab_name", "ошибка удаления");
                return View(item);
            }
        }
        public ActionResult EditLab(int id)
        {
            NewLab lab = UnitOfWork.Labs.Get(id);
            return View(lab);
        }
        [HttpPost]
        public ActionResult EditLab(NewLab item)
        {
            try
            {
                UnitOfWork.Labs.Update(item);
                return RedirectToAction("LabsOnDisciplineList", new { discipline_id = item.discipline_id });
            }
            catch
            {
                ModelState.AddModelError("lab_name", "ошибка редактирования");
                return View(item);
            }
        }
        public ActionResult ChangeLabStatus(int id)
        {
            LabProgress lab_progress  = UnitOfWork.LabProgress.Get(id);
            lab_progress.Statuses = LabProgress.GetAllStatus();
            return View(lab_progress);
        }
        [HttpPost]
        public ActionResult ChangeLabStatus(LabProgress item)
        {
            string id = User.Identity.GetUserId();
            UnitOfWork.LabProgress.Update(item);
            return RedirectToAction("Labs", new { discipline_id = item.discipline_id, subgroup_id=item.subgroop_id });
        }
    }
}

ElectronDecanat/ElectronDecanat/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title – приложение ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/Scripts/jquery-1.10.2.min.js")
    @Scripts.Render("~/Scripts/jquery.dataTables.min.js")
    <link href="@Url.Content("~/Content/dropdownMenu.css")" rel="stylesheet" type="text/css" />
    <script type="text/javascript">
        window.russian_lang =
            {
                language:
                {
                    "processing": "Подождите...",
                    "search": "Поиск:",
                    "lengthMenu": "Показать _MENU_ записей",
                    "info": "Записи с _START_ до _END_ из _TOTAL_ записей",
                    "infoEmpty": "Записи с 0 до 0 из 0 записей",
                    "infoFiltered": "(отфильтровано из _MAX_ записей)",
                    "infoPostFix": "",
                    "loadingRecords": "Загрузка записей...",
                    "zeroRecords": "Записи отсутствуют.",
                    "emptyTable": "В таблице отсутствуют данные",
                    "paginate":
                    {
                        "first": "Первая",
                        "previous": "Предыдущая",
                        "next": "Следующая",
                        "last": "Последняя"
                    },
                    "aria":
                    {
                        "sortAscending": ": активировать для сортировки столбца по возрастанию",
                        "sortDescending": ": активировать для сортировки столбца по убыванию"
                    }
                }
            }
    </script>
    <link rel="stylesheet" href=@Url.Content("~/Content/jquery.dataTables.min.css")>
    <style>
        footer
        {
            position:fixed;
            top:91%;
            left:87%;
        }
    </style>

</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Электронный деканат", "Index", "Main", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Домашняя страница", "Index", "Main")</li>
                    <li>
                        <a href="#">Преподаватель</a>
                        <ul class="dropdown-menu nav navbar-nav">
                            <li>@Html.ActionLink("Успеваемость", "Index", "Teacher")</li>
                            <li>@Html.ActionLink("Редактирование лабораторных", "LabsList", "Teacher")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Администратор</a>
                        <ul class="dropdown-menu nav navbar-nav">
                            <li>@Html.ActionLink("Факультеты", "Facultes", "Admin")</li>
                            <li>@Html.ActionLink("Преподаватели", "Teachers", "Admin")</li>
                            <li>@Html.ActionLink("Права доступа", "Users", "Admin")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Деканат</a>
                        <ul class="dropdown-menu nav navbar-nav">
                            <li>@Html.ActionLink("Факультеты", "Facultes", "Dekan")</li>
                        </ul>
                    </li>
                    <li>
                        <a href="#">Студент</a>
                        <ul class="dropdown-menu nav navbar-nav">
                            <li>@Html.ActionLink("Поиск", "Index", "Student")</li>
                        </ul>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        
        <footer>
            <hr />
            <p>&copy; @DateTime.Now.Year – приложение ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>